name: Build and Release with Nuitka

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: pdf-linux
          - os: windows-latest
            artifact_name: pdf-windows.exe
          - os: macos-latest
            artifact_name: pdf-macos

    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "nuitka>=2.6" ordered-set zstandard

      - name: Install clcache (Windows)
        if: runner.os == 'Windows'
        run: pip install clcache
        shell: bash

      - name: Setup clcache environment (Windows)
        if: runner.os == 'Windows'
        run: echo "CLCACHE_DIR=${{ github.workspace }}\\.clcache" >> $GITHUB_ENV
        shell: bash

      - name: Cache clcache (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: .clcache
          key: clcache-windows-${{ hashFiles('requirements.txt') }}-${{ hashFiles('main.py') }}
          restore-keys: |
            clcache-windows-${{ hashFiles('requirements.txt') }}-
            clcache-windows-

      - name: Install platform dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache patchelf

      - name: Install platform dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install ccache

      - name: Build with Nuitka (Linux)
        if: runner.os == 'Linux'
        run: |
          python -m nuitka \
            --mode=onefile \
            --assume-yes-for-downloads \
            --output-filename=${{ matrix.artifact_name }} \
            --enable-plugin=tk-inter \
            --linux-icon=icon.png \
            --company-name="YourCompany" \
            --product-name="PDF Tool" \
            --file-version=1.0.0 \
            --product-version=1.0.0 \
            --lto=no \
            --jobs=2 \
            main.py

      - name: Build with Nuitka (macOS)
        if: runner.os == 'macOS'
        run: |
          python -m nuitka \
            --mode=app \
            --assume-yes-for-downloads \
            --output-filename=${{ matrix.artifact_name }} \
            --enable-plugin=tk-inter \
            --macos-app-icon=icon.icns \
            --company-name="YourCompany" \
            --product-name="PDF Tool" \
            --file-version=1.0.0 \
            --product-version=1.0.0 \
            --lto=no \
            --jobs=2 \
            main.py

      - name: Build with Nuitka (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m nuitka ^
            --mode=onefile ^
            --assume-yes-for-downloads ^
            --output-filename=${{ matrix.artifact_name }} ^
            --windows-console-mode=disable ^
            --enable-plugin=tk-inter ^
            --windows-icon-from-ico=icon.ico ^
            --company-name="YourCompany" ^
            --product-name="PDF Tool" ^
            --file-version=1.0.0.0 ^
            --product-version=1.0.0.0 ^
            --copyright="Copyright 2025" ^
            --lto=no ^
            --low-memory ^
            --jobs=1 ^
            main.py
        shell: cmd
        env:
          CLCACHE_CL: cl.exe

      - name: Make executable (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x ${{ matrix.artifact_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./release-artifacts

      - name: Verify artifacts
        run: |
          ls -lah ./release-artifacts/
          file ./release-artifacts/* || true

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./release-artifacts/pdf-linux
            ./release-artifacts/pdf-windows.exe
            ./release-artifacts/pdf-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
