name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pdf-linux
            build_type: nuitka
          - os: windows-latest
            artifact_name: pdf-windows.exe
            build_type: pyinstaller
          - os: macos-latest
            artifact_name: pdf-macos.app
            build_type: nuitka

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Nuitka (Linux/macOS)
        if: matrix.build_type == 'nuitka'
        run: pip install "nuitka>=2.6" ordered-set zstandard

      - name: Install PyInstaller (Windows)
        if: matrix.build_type == 'pyinstaller'
        run: pip install pyinstaller

      - name: Install platform dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache patchelf

      - name: Install platform dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install ccache

      - name: Build with Nuitka (Linux)
        if: runner.os == 'Linux'
        run: |
          python -m nuitka \
            --onefile \
            --assume-yes-for-downloads \
            --output-filename=${{ matrix.artifact_name }} \
            --enable-plugin=tk-inter \
            --company-name="YourCompany" \
            --product-name="PDF Tool" \
            --file-version=1.0.0 \
            --product-version=1.0.0 \
            --lto=no \
            main.py

      - name: Build with Nuitka (macOS)
        if: runner.os == 'macOS'
        run: |
          python -m nuitka \
            --standalone \
            --macos-create-app-bundle \
            --assume-yes-for-downloads \
            --macos-app-name="PDF Tool" \
            --enable-plugin=tk-inter \
            --company-name="YourCompany" \
            --product-name="PDF Tool" \
            --file-version=1.0.0 \
            --product-version=1.0.0 \
            --lto=no \
            main.py

      - name: Build with PyInstaller (Windows)
        if: runner.os == 'Windows'
        run: |
          pyinstaller ^
            --onefile ^
            --windowed ^
            --name=pdf-windows ^
            --icon=icon.ico ^
            main.py
        shell: cmd

      - name: Make executable (Linux)
        if: runner.os == 'Linux'
        run: chmod +x ${{ matrix.artifact_name }}

      - name: Upload artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: pdf-linux
          path: ${{ matrix.artifact_name }}

      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: pdf-windows.exe
          path: dist/pdf-windows.exe

      - name: Zip macOS app (macOS)
        if: runner.os == 'macOS'
        run: |
          cd main.app
          zip -r ../pdf-macos.zip .
          cd ..

      - name: Upload artifact (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: pdf-macos.zip
          path: pdf-macos.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Prepare release files
        run: |
          mkdir -p ./release-files
          find ./artifacts -type f -exec cp {} ./release-files/ \;
          ls -lah ./release-files/

      - name: Get version
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ./release-files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
